# docs.spring.io/spring-boot/docs/ ... 매뉴얼 참고
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # if 'member' table exists, drop. And then create 'member' table!
      #ddl-auto: none    # table drop X. 한 번 넣어두면, 계속 남아있어 그 데이터 사용 가능.
    properties:
      hibernate:
#        show_sql: true        # stdout으로 출력
        format_sql: true

  thymeleaf:
#    name: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
#    cache: false

logging:
  level:
    org.hibernate.SQL: debug  # JPA과 hibernate가 남기는 SQL을 모두 볼 수 있음(로그로 출력)
#    org.hibernate.type: trace
